[phases.setup]
nixPkgs = ["python311", "gcc", "nodejs_20", "npm"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "./railway-build.sh"
]

[start]
cmd = "python app.py"
